### ISSUE TITLE
Carl Masäk fixes

### ISSUE THREAD

**Issue by eiro** [karlhorky/awesome-speakers#116]
sorry, just reviewed the page and 

about  Carl Masäk:
* the guy on the picture is Sawyer X
* Carl in from Malmö (city)

the Bulgaria title was destroyed in the process so Sofia is now in Cz ... sorry

**Comment by SaraVieira** [comment]
Hello !

can you fix this ? :/

**Comment by eiro** [comment]
On Thu, Jan 04, 2018 at 07:04:00AM -0800, Sara Vieira wrote:
> Hello !
> can you fix this ? :/

lack of time for the moment

**Comment by karlhorky** [comment]
Where is Carl Masäk? Can't find this person in the text of the page.

**Comment by karlhorky** [comment]
Closing for now since I cannot find this person.
