### ISSUE TITLE
Please update "Gregor Adams"

### ISSUE THREAD

**Issue by pixelass** [karlhorky/awesome-speakers#158]
Thank you for including me in this list. It is an honor.

The codepen link is invalid since I left codepen. Since since then it has been used by a spammer.  
I want to make sure people don't assume the account has anything to do with me (the account has now been deleted). 

```
  Gregor Adams
  Topics: Fractals, CSS, JavaScript, Web Animations
- codepen.io/pixelass
+ github.com/pixelass
```

Thank you.

**Comment by SaraVieira** [comment]
Hey !

Updated and sorry for the trouble
