### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by ColinEberhardt** [karlhorky/awesome-speakers#37]
As this awesome list is about people, not projects, I think you need to be clear about the requirements for being added to the list - as it is a lot more personal!

Are you expecting that anyone can be added or add themselves? Or are there criteria for being ‘awesome’?

**Comment by SaraVieira** [comment]
Hey!

We are thinking of this as with only two guidelines :
You must either know the person or seen a talk by them and if you believe that they are awesome it can be added because I don't believe there really is a definition of awesome
Also let the person know that they will be added

**Comment by SaraVieira** [comment]
If this sounds great I will create a contribution file today

**Comment by ColinEberhardt** [comment]
> Also let the person know that they will be added

I think this is important from a privacy perspective. I'd be happy to be added to this list - but would prefer that I was informed of the addition. Privacy is important (even for people who put themselves 'out there' as speakers)

**Comment by SaraVieira** [comment]
Exacly ! They may notr want to speak anymore even 

I will create the document today

**Comment by karlhorky** [comment]
Thanks @SaraVieira and @ColinEberhardt!

I actually didn't have such strict guidelines in mind when I first created it. I just wanted to put together a list of people that I knew that did talks to make it easier to organize meetups. And once I add people, I've made sure it's ok with them and asked them if they can also recommend anyone. Other than that, I've also added speakers that I've seen on conference lists. This has worked well so far. I don't want to have too much overhead to adding people to the list, to keep the barrier to contribution low.

I think if the list grows to a large size and it becomes unusable, or if there are other problems that come up, then stricter guidelines will become important. For now, we can offer them as light recommendations.

**Comment by SaraVieira** [comment]
@karlhorky Should this be created or we can just handle this ?

**Comment by karlhorky** [comment]
Why don't you write a quick one with the two requirements you described above:

- you know the person / have seen a talk by them and think they're awesome
- let the person know

And then we can just let it be organically discovered and/or link to it if needed. So not pushing too hard, but offer some light recommendations.
