### ISSUE TITLE
Add Github avatar?

### ISSUE THREAD

**Issue by xtuc** [karlhorky/awesome-speakers#6]
Would look better IMO. What do you think?

**Comment by karlhorky** [comment]
Can you PR a suggestion (just two or three speakers, so I get an idea for how it will look)? Also, what about people without a picture?

**Comment by karlhorky** [comment]
I like the idea though if we can get a nice representation though :)

**Comment by xtuc** [comment]
yes

**Comment by xtuc** [comment]
I made the PR #8, renderded: https://github.com/xtuc/awesome-speakers/blob/82188c54b78679a9eefa9656392df8403def4a46/README.md

**Comment by karlhorky** [comment]
Hm, ok, this is coming along...

<img width="294" alt="screen shot 2017-11-03 at 12 23 12" src="https://user-images.githubusercontent.com/1935696/32371731-456c49d2-c092-11e7-9702-4b28f708dc43.png">

Can we design this a bit more? Maybe like having the avatars floated to the left or the right? So that they don't take up more vertical space? Also, maybe we don't need the bullet point anymore?

The idea of what to do with people without avatars also plays a role here in the design.

**Comment by karlhorky** [comment]
Another idea would also be to use the Twitter images instead of the GitHub ones, because the links go to Twitter...?

**Comment by xtuc** [comment]
Yes I agree. I used the GitHub picture because I know you can reliability use them, but we can try with Twitter.

**Comment by xtuc** [comment]
I don't know what to make two columns (tried with float and flexbox). Here is a [try with a table](https://github.com/xtuc/awesome-speakers/blob/cc6220621217c76415137ba32a9a87e988bad415/README.md#strasbourg), what do you think?

**Comment by tlakomy** [comment]
Table looks great IMO :)

**Comment by karlhorky** [comment]
Ah a table, that doesn't look too bad. Can we get rid of the first row?

<img width="771" alt="screen shot 2017-11-03 at 14 00 47" src="https://user-images.githubusercontent.com/1935696/32374820-8ed20780-c09f-11e7-99c5-38d34d5850d9.png">

Would it have a table for each speaker? The syntax kind of sucks to have to write...

<img width="1116" alt="screen shot 2017-11-03 at 14 01 00" src="https://user-images.githubusercontent.com/1935696/32374932-0ca3fd4e-c0a0-11e7-9d90-1247edcb89ca.png">

**Comment by xtuc** [comment]
I had to keep the first row because it would break the table otherwise, maybe there's a way to get red of it.

The table is indeed more verbose, is it worth the picture?

**Comment by robinpokorny** [comment]
On GitHub you can float an image with simple `align="left"`. 70px is about three lines. It can, however, break easily when there are more lines.

```md
<img src="https://pbs.twimg.com/profile_images/678903331176214528/TQTdqGwD_400x400.jpg" height="70px" width="auto" align="left" />

Artem Sapegin  
Topics: Style guides, UI, CSS  
https://twitter.com/iamsapegin
```

<img src="https://pbs.twimg.com/profile_images/678903331176214528/TQTdqGwD_400x400.jpg" height="70px" width="auto" align="left" />

Artem Sapegin  
Topics: Style guides, UI, CSS  
https://twitter.com/iamsapegin

**Comment by xtuc** [comment]
@robinpokorny looks awesome :100:

![screenshot from 2017-11-03 14-20-27](https://user-images.githubusercontent.com/1493671/32375509-298aeb50-c0a2-11e7-824e-69f00e13ebb6.png)

It is also easier to use.

**Comment by karlhorky** [comment]
Yep, looks great @robinpokorny @xtuc . Update the PR for the latest content and I'll accept.

**Comment by karlhorky** [comment]
Closing this, will continue discussion in #8. Thanks for staying on this!
